## Homework

In [1]:
import numpy as np

### Drill (1 балл)

Task 1.

Initialize the arrays of the following forms with zeros

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [2]:
shapes = [(5,),(5,1),(10,2),(3,6,2),(4,3,2,1)]

vectors = [ np.zeros(shape) for shape in shapes]

for vec in vectors:
    print(vec.shape)

(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)


Task 2.

Initialize arrays of the same shapes with ones and render them to an integer form:

In [3]:
vectors = [ np.ones(shape).astype(int) for shape in shapes ]

for vec in vectors:
    print(vec.shape)
    
print(vectors[0].dtype)

(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)
int64


Task 3.

Execute on the vectors above 'reshape' to 'form'
* with two components
* with three components
* with four components

In [4]:
def cal_shape(shape, num):
    '''
    reshape vector with num of components
    '''
    if len(shape) == num:
        return shape
    elif len(shape) < num:
        new_shape = [1] * num
        new_shape[:len(shape)] = list(shape)
        return tuple(new_shape)
    else:
        new_shape = list(shape)
        num_multiply = len(shape) - num
        new_shape = [ np.prod(new_shape[:num_multiply+1]) ] + new_shape[num_multiply+1:]
        return tuple(new_shape)

In [5]:
for vec in vectors:
    for i in [2,3,4]:
        shape = cal_shape(vec.shape, i)
        vec0 = vec.reshape(shape)
        print(f"the shape for {vec.shape} with {i} components is {vec0.shape}")

the shape for (5,) with 2 components is (5, 1)
the shape for (5,) with 3 components is (5, 1, 1)
the shape for (5,) with 4 components is (5, 1, 1, 1)
the shape for (5, 1) with 2 components is (5, 1)
the shape for (5, 1) with 3 components is (5, 1, 1)
the shape for (5, 1) with 4 components is (5, 1, 1, 1)
the shape for (10, 2) with 2 components is (10, 2)
the shape for (10, 2) with 3 components is (10, 2, 1)
the shape for (10, 2) with 4 components is (10, 2, 1, 1)
the shape for (3, 6, 2) with 2 components is (18, 2)
the shape for (3, 6, 2) with 3 components is (3, 6, 2)
the shape for (3, 6, 2) with 4 components is (3, 6, 2, 1)
the shape for (4, 3, 2, 1) with 2 components is (24, 1)
the shape for (4, 3, 2, 1) with 3 components is (12, 2, 1)
the shape for (4, 3, 2, 1) with 4 components is (4, 3, 2, 1)


Task 4.

For the vector below, calculate it
* Maximum 1 axis
* Minimum 0 axis
* Sum in all axes
* Average on 0 axis
* Median 1 axis

In [8]:
v = np.random.randint(0, 9, size=(5, 7))
print(v)

[[4 7 7 5 7 5 1]
 [7 7 4 1 5 8 5]
 [8 2 3 5 5 6 1]
 [1 3 6 7 0 2 5]
 [2 7 4 8 6 3 5]]


In [9]:
print(v.max(axis=1))
print(v.min(axis=0))
print(v.sum())
print(v.mean(axis=0))
print(np.median(v,axis=1))

[7 8 8 7 8]
[1 2 3 1 0 2 1]
162
[4.4 5.2 4.8 5.2 4.6 4.8 3.4]
[5. 5. 5. 3. 5.]


Task 5.

For the same vector 'v' derive
* Its shape
* 0 component of its 'shape'
* 1 component of its 'shape'

In [10]:
v.shape, v.shape[0], v.shape[1]

((5, 7), 5, 7)

Task 6.

For the same vector, derive
* All numbers greater than 5
* All numbers less than 7 in reverse order
* All numbers greater than 3, which are divided by 4 without residue
* All numbers whose remainder from dividing by 5 is 3
* Maximum index
* Minimum index
* List with indexes of the elements of the sorted array in the original (unsorted)

In [11]:
print(v[v>5])
print(v[v<7][::-1])
print(v[(v>3) & (v%4 == 0)])
print(v[v%5 == 3])
print(v.argmax())
print(v.argmin())
print(v.argsort(axis=None))

[7 7 7 7 7 8 8 6 6 7 7 8 6]
[5 3 6 4 2 5 2 0 6 3 1 1 6 5 5 3 2 5 5 1 4 1 5 5 4]
[4 4 8 8 4 8]
[8 8 3 3 8 3]
12
25
[25  6 21 10 20 28 26 15 22 33 16  0 30  9 27 18 17 13  3 11  5 34 23 32
 19  8  7 24  4  2 29  1 14 12 31]


Task 7.

Perform the following operations on the vector (independently, it is not necessary to do this in sequence):
* Multiply it by 3
* Divide by 7
* Elevate to the degree of $frac{2}{3}$
* Count $sin$ from it
* Count $log$ from it

In [12]:
v = np.random.randint(1,100,size=10)
print(v)

print(v * 3)
print(v / 7)
print(np.power(v, 2/3))
print(np.sin(v))
print(np.log(v))

[47 99 97 49 74 27 93 65 82 43]
[141 297 291 147 222  81 279 195 246 129]
[ 6.71428571 14.14285714 13.85714286  7.         10.57142857  3.85714286
 13.28571429  9.28571429 11.71428571  6.14285714]
[13.02362568 21.40047747 21.11127629 13.39051828 17.62602898  9.
 20.52683379 16.16623563 18.87451938 12.27379797]
[ 0.12357312 -0.99920683  0.37960774 -0.95375265 -0.98514626  0.95637593
 -0.94828214  0.82682868  0.31322878 -0.83177474]
[3.8501476  4.59511985 4.57471098 3.8918203  4.30406509 3.29583687
 4.53259949 4.17438727 4.40671925 3.76120012]


### Different initializations + indexing (3 points)

Task 8.

Build a square of $3 \times 3$ from odd numbers

In [13]:
odd_square = np.array([ 1+2*i for i in range(9) ])
odd_square = odd_square.reshape(3,3)
print(odd_square)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Task 9.

Construct a square of $4 \times 4$ from even numbers in reverse order

In [14]:
even_square = np.array([0+2*i for i in range(16)])
even_square = even_square[::-1].reshape(4,4)
print(even_square)

[[30 28 26 24]
 [22 20 18 16]
 [14 12 10  8]
 [ 6  4  2  0]]


Task 10.

Build a grid of coordinates $11 \times 11$ with a dot $(0.0)$ in the center and a step of $0.1$ between the cells

In [15]:
x = np.linspace(-0.5,0.5,11)
y = np.linspace(-0.5,0.5,11)
xv, yv = np.meshgrid(x,y)

lines = []
for i in range(11):
    line = [ (round(ai,2), round(aj,2)) for ai, aj in zip(xv[i], yv[i])]
    lines.append(line)
    
print(lines)

[[(-0.5, -0.5), (-0.4, -0.5), (-0.3, -0.5), (-0.2, -0.5), (-0.1, -0.5), (0.0, -0.5), (0.1, -0.5), (0.2, -0.5), (0.3, -0.5), (0.4, -0.5), (0.5, -0.5)], [(-0.5, -0.4), (-0.4, -0.4), (-0.3, -0.4), (-0.2, -0.4), (-0.1, -0.4), (0.0, -0.4), (0.1, -0.4), (0.2, -0.4), (0.3, -0.4), (0.4, -0.4), (0.5, -0.4)], [(-0.5, -0.3), (-0.4, -0.3), (-0.3, -0.3), (-0.2, -0.3), (-0.1, -0.3), (0.0, -0.3), (0.1, -0.3), (0.2, -0.3), (0.3, -0.3), (0.4, -0.3), (0.5, -0.3)], [(-0.5, -0.2), (-0.4, -0.2), (-0.3, -0.2), (-0.2, -0.2), (-0.1, -0.2), (0.0, -0.2), (0.1, -0.2), (0.2, -0.2), (0.3, -0.2), (0.4, -0.2), (0.5, -0.2)], [(-0.5, -0.1), (-0.4, -0.1), (-0.3, -0.1), (-0.2, -0.1), (-0.1, -0.1), (0.0, -0.1), (0.1, -0.1), (0.2, -0.1), (0.3, -0.1), (0.4, -0.1), (0.5, -0.1)], [(-0.5, 0.0), (-0.4, 0.0), (-0.3, 0.0), (-0.2, 0.0), (-0.1, 0.0), (0.0, 0.0), (0.1, 0.0), (0.2, 0.0), (0.3, 0.0), (0.4, 0.0), (0.5, 0.0)], [(-0.5, 0.1), (-0.4, 0.1), (-0.3, 0.1), (-0.2, 0.1), (-0.1, 0.1), (0.0, 0.1), (0.1, 0.1), (0.2, 0.1), (0.3, 0.

Task 11.

Tiling a mesh of $8\times8$ with $0$ and $1$ in a staggered manner, a cage with an index of $(0.0)$ is paved with $1$

In [17]:
mesh = np.zeros((8,8))
mesh[::2, ::2] = 1
mesh[1::2, ::]

### Operations + aggregations (3 points)

Task 16.

A sample of ${X_i}$ of some random variable $X$ is given, it is necessary to estimate
* Expected $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ of this random variable
* Variance $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ of this random variable

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return #


def dispersion(x):
    assert len(x) > 0
    return #

In [ ]:
def expected_value_np(x):
    return np.mean(x)

In [ ]:
def dispersion_np(x):
    return np.var(x)

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

### Different actions with matrices (3 points)

Task 21.

A matrix of size $(32, 3, 16, 16)$ filled with random numbers from 0 to 9 is given. Use **exactly two** transformations to make it look like $(32, 1)$. When you run a task, you can create auxiliary matrices!

In [ ]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
print(data.shape)

Task 22.

There are two matrices $m_1$ in size $(32, 256)$ and $m_2$ in size $(32, 512)$, as well as two auxiliary matrices $W_1$ in size $(256, 32)$ and $W_2$ in size $(512, 16)$. Using the **all** data of the matrix, make the output **exactly one** matrix of size $(32, 32)$

In [ ]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

a=np.dot(m1.T,m2)
b=np.dot(a.T,W1)
c=np.dot(b.T,W2)
d=np.dot(m2,W2)
e=np.dot(c,d.T)
result = e

assert result.shape == (32, 32)