## Homework

In [2]:
import numpy as np

### Drill (1 балл)

Task 1.

Initialize the arrays of the following forms with zeros

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [3]:
SHAPES=[5,(5,1),(10,2),(3,6,2),(4,3,2,1)]

In [4]:
rz=[np.zeros(i) for i in SHAPES]
for i in range(len(rz)):
    print(rz[i].shape)
#Sample
print(rz[0])

(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)
[0. 0. 0. 0. 0.]


Task 2.

Initialize arrays of the same shapes with ones and render them to an integer form:

In [5]:
ro=[np.ones(i).astype(int) for i in SHAPES]
for i in range(len(ro)):
    print(ro[i].shape)
#Sample
print(ro[0])


(5,)
(5, 1)
(10, 2)
(3, 6, 2)
(4, 3, 2, 1)
[1 1 1 1 1]


Task 3.

Execute on the vectors above 'reshape' to 'form'
* with two components
* with three components
* with four components

In [6]:
#(5,)
#reshaping to same thing if the component count is same
ro[0]=ro[0].reshape((5,1))
ro[0]=ro[0].reshape((5,1,1))
ro[0]=ro[0].reshape((5,1,1,1))
print(ro[0].shape)

#(5,1)
ro[1]=ro[1].reshape((5,1))
ro[1]=ro[1].reshape((5,1,1))
ro[1]=ro[1].reshape((5,1,1,1))
print(ro[1].shape)

#(10,2)
ro[2]=ro[2].reshape((10,2))
ro[2]=ro[2].reshape((10,2,1))
ro[2]=ro[2].reshape((10,2,1,1))
print(ro[2].shape)

#(3,6,2)
ro[3]=ro[3].reshape((36,1))
ro[3]=ro[3].reshape((3,6,2))
ro[3]=ro[3].reshape((3,6,2,1))
print(ro[3].shape)

#(4,3,2,1)
ro[4]=ro[4].reshape((24,1))
ro[4]=ro[4].reshape((12,2,1))
ro[4]=ro[4].reshape((4,3,2,1))
print(ro[4].shape)




(5, 1, 1, 1)
(5, 1, 1, 1)
(10, 2, 1, 1)
(3, 6, 2, 1)
(4, 3, 2, 1)


Task 4.

For the vector below, calculate it
* Maximum 1 axis
* Minimum 0 axis
* Sum in all axes
* Average on 0 axis
* Median 1 axis

In [7]:
v = np.random.randint(0, 9, size=(5, 7))   
v

array([[4, 1, 1, 3, 2, 1, 3],
       [0, 7, 5, 5, 4, 5, 7],
       [1, 7, 0, 6, 6, 8, 8],
       [6, 4, 1, 0, 3, 7, 4],
       [0, 4, 5, 6, 4, 0, 7]])

In [8]:
#Maximum 1 axis
print(np.amax(v,axis=1))

#Minimum 0 axis
print(np.amin(v,axis=0))

#Sum all axes
print(np.sum(v,axis=0))
print(np.sum(v,axis=1))
print(np.sum(v))

#Average on axis 0
print(np.mean(v,axis=0))

#Median on axis 1
print(np.median(v,axis=1))


[4 7 8 7 7]
[0 1 0 0 2 0 3]
[11 23 12 20 19 21 29]
[15 33 36 25 26]
135
[2.2 4.6 2.4 4.  3.8 4.2 5.8]
[2. 5. 6. 4. 4.]


Task 5.

For the same vector 'v' derive
* Its shape
* 0 component of its 'shape'
* 1 component of its 'shape'

In [9]:
print(v.shape)
print(v.shape[0])
print(v.shape[1])

(5, 7)
5
7


Task 6.

For the same vector, derive
* All numbers greater than 5
* All numbers less than 7 in reverse order
* All numbers greater than 3, which are divided by 4 without residue
* All numbers whose remainder from dividing by 5 is 3
* Maximum index
* Minimum index
* List with indexes of the elements of the sorted array in the original (unsorted)

In [10]:
print(v[v>5])
print(v[v<7][::-1])
print(v[(v>3) & (v%4==0)])
print(v[v%5==3])
print(np.argmax(v))
print(np.argmin(v))
print(np.argsort(v))

[7 7 7 6 6 8 8 6 7 6 7]
[0 4 6 5 4 0 4 3 0 1 4 6 6 6 0 1 5 4 5 5 0 3 1 2 3 1 1 4]
[4 4 8 8 4 4 4 4]
[3 3 8 8 3]
19
7
[[1 2 5 4 3 6 0]
 [0 4 2 3 5 1 6]
 [2 0 3 4 1 5 6]
 [3 2 4 1 6 0 5]
 [0 5 1 4 2 3 6]]


Task 7.

Perform the following operations on the vector (independently, it is not necessary to do this in sequence):
* Multiply it by 3
* Divide by 7
* Elevate to the degree of $frac{2}{3}$
* Count $sin$ from it
* Count $log$ from it

In [11]:
print(v*3)
print(v/7)
print(np.power(v,2/3))
print(np.sin(v))
print(np.log(v))

[[12  3  3  9  6  3  9]
 [ 0 21 15 15 12 15 21]
 [ 3 21  0 18 18 24 24]
 [18 12  3  0  9 21 12]
 [ 0 12 15 18 12  0 21]]
[[0.57142857 0.14285714 0.14285714 0.42857143 0.28571429 0.14285714
  0.42857143]
 [0.         1.         0.71428571 0.71428571 0.57142857 0.71428571
  1.        ]
 [0.14285714 1.         0.         0.85714286 0.85714286 1.14285714
  1.14285714]
 [0.85714286 0.57142857 0.14285714 0.         0.42857143 1.
  0.57142857]
 [0.         0.57142857 0.71428571 0.85714286 0.57142857 0.
  1.        ]]
[[2.5198421  1.         1.         2.08008382 1.58740105 1.
  2.08008382]
 [0.         3.65930571 2.92401774 2.92401774 2.5198421  2.92401774
  3.65930571]
 [1.         3.65930571 0.         3.30192725 3.30192725 4.
  4.        ]
 [3.30192725 2.5198421  1.         0.         2.08008382 3.65930571
  2.5198421 ]
 [0.         2.5198421  2.92401774 3.30192725 2.5198421  0.
  3.65930571]]
[[-0.7568025   0.84147098  0.84147098  0.14112001  0.90929743  0.84147098
   0.14112001]
 [ 0.   

C:\Users\ABDULA~1\AppData\Local\Temp/ipykernel_16748/1333596073.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(v))


### Different initializations + indexing (3 points)

Task 8.

Build a square of $3 \times 3$ from odd numbers

In [12]:
arr=np.arange(1,19,2).reshape((3,3))
print(arr)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Task 9.

Construct a square of $4 \times 4$ from even numbers in reverse order

In [13]:
arr=np.arange(2,33,2).reshape(4,4)
print(arr)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task 10.

Build a grid of coordinates $11 \times 11$ with a dot $(0.0)$ in the center and a step of $0.1$ between the cells

In [30]:
x=[float(i) for i in range(-5,6,1)]
y=[i/10 for i in range(-5,6,1)]
xa,xb=np.meshgrid(x,y,indexing='ij')
print(xa+xb)

[[-5.5 -5.4 -5.3 -5.2 -5.1 -5.  -4.9 -4.8 -4.7 -4.6 -4.5]
 [-4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7 -3.6 -3.5]
 [-3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5]
 [-2.5 -2.4 -2.3 -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5]
 [-1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9 -0.8 -0.7 -0.6 -0.5]
 [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5]
 [ 0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5]
 [ 1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5]
 [ 2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5]
 [ 3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5]
 [ 4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5]]


Task 11.

Tiling a mesh of $8\times8$ with $0$ and $1$ in a staggered manner, a cage with an index of $(0.0)$ is paved with $1$

In [23]:
mesh=np.ones((8,8),dtype=int)
mesh[1::2,::2]=0 # 0-1-0-1
mesh[::2,1::2]=0 # 1-0-1-0
print(mesh)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### Operations + aggregations (3 points)

Task 16.

A sample of ${X_i}$ of some random variable $X$ is given, it is necessary to estimate
* Expected $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ of this random variable
* Variance $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ of this random variable

In [15]:
def expected_value(x):
    assert len(x) > 0
    return 1/len(x) * np.sum(x) 


def dispersion(x):
    assert len(x) > 0
    return 1/len(x) * np.sum((x-expected_value(x))**2 )

In [16]:
def expected_value_np(x):
    return np.mean(x)

In [17]:
def dispersion_np(x):
    return np.var(x)

In [18]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

### Different actions with matrices (3 points)

Task 21.

A matrix of size $(32, 3, 16, 16)$ filled with random numbers from 0 to 9 is given. Use **exactly two** transformations to make it look like $(32, 1)$. When you run a task, you can create auxiliary matrices!

In [19]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
data=data.reshape((32,-1))
aux=np.random.randint(0,10,size=(16*16*3,1))
data=np.dot(data,aux)
print(data.shape)

(32, 1)


Task 22.

There are two matrices $m_1$ in size $(32, 256)$ and $m_2$ in size $(32, 512)$, as well as two auxiliary matrices $W_1$ in size $(256, 32)$ and $W_2$ in size $(512, 16)$. Using the **all** data of the matrix, make the output **exactly one** matrix of size $(32, 32)$

In [20]:
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

a=np.dot(m1.T,m2)
b=np.dot(a.T,W1)
c=np.dot(b.T,W2)
d=np.dot(m2,W2)
e=np.dot(c,d.T)
result = e

assert result.shape == (32, 32)